const environment = {
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  NEXT_AUTH_SECRET: process.env.NEXT_AUTH_SECRET,
  NEXT_PUBLIC_MIDTRANS_SANP_URL: process.env.NEXT_PUBLIC_MIDTRANS_SANP_URL,
  NEXT_PUBLIC_MIDTRANS_CLIENT_KEY: process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY,
};

export default environment;
